[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/version"
healthcheckTimeout = 60
healthcheckInitialDelay = 300
restartPolicyType = "never"
restartPolicyMaxRetries = 0

# Railwayプラットフォーム用の設定
[env]
PORT = { default = "50021" }
HOST = { default = "0.0.0.0" }

[[services]]
name = "voicevox-engine"
type = "web"

# メモリとCPUの割り当てを増加
[resources]
memory = 6
vCpu = 4
