[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/version"
healthcheckTimeout = 600
healthcheckInitialDelay = 900
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "voicevox-engine"
