[build]
builder = "dockerfile"

[deploy]
startCommand = "./voicevox_engine_linux-x64/run --host 0.0.0.0 --port $PORT"
healthcheckPath = "/version"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "voicevox-engine"
